# Generated by Django 5.2.1 on 2025-06-02 11:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classmate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('photo', models.ImageField(upload_to='classmates/', verbose_name='Фото')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Сокурсник',
                'verbose_name_plural': 'Сокурсники',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('role', models.CharField(choices=[('academic', 'Академический руководитель'), ('manager', 'Менеджер программы')], max_length=20, verbose_name='Роль')),
                ('photo', models.ImageField(upload_to='managers/', verbose_name='Фото')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
            ],
            options={
                'verbose_name': 'Руководитель/Менеджер',
                'verbose_name_plural': 'Руководители/Менеджеры',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название программы')),
                ('url', models.URLField(verbose_name='Ссылка на страницу ОП')),
                ('description', models.TextField(verbose_name='Описание')),
                ('what_ill_learn', models.TextField(verbose_name='Что я буду изучать')),
                ('skills', models.TextField(verbose_name='Чему научусь')),
                ('advantages', models.TextField(verbose_name='Преимущества программы')),
                ('prospects', models.TextField(verbose_name='Перспективы после обучения')),
            ],
            options={
                'verbose_name': 'Образовательная программа',
                'verbose_name_plural': 'Образовательные программы',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('photo', models.ImageField(upload_to='students/', verbose_name='Фото')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('resume', models.FileField(upload_to='resumes/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx'])], verbose_name='Резюме')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
        ),
    ]
